# Generated by Django 3.0.1 on 2019-12-30 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choiceID',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='question',
            name='questionNumber',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
