# Generated by Django 3.0.1 on 2019-12-30 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191229_1741'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0005_auto_20191229_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='teacher',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('students', models.ManyToManyField(to='users.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='homework.Course'),
            preserve_default=False,
        ),
    ]
