# Generated by Django 3.0.1 on 2019-12-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_auto_20191229_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
    ]
