# Generated by Django 3.0.1 on 2020-01-02 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0009_auto_20191231_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradedQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homework.Quiz')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
