# Generated by Django 3.0.1 on 2020-01-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0012_auto_20200102_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choiceID',
            new_name='choice_number',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homework.Question'),
            preserve_default=False,
        ),
    ]
