# Generated by Django 3.0.1 on 2020-01-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0014_quiz_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionNumber',
            new_name='question_number',
        ),
    ]
