# Generated by Django 3.0.1 on 2020-01-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0015_auto_20200103_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quiz',
            new_name='question',
        ),
    ]
