# Generated by Django 3.0.1 on 2019-12-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher')], default='ST', max_length=2),
        ),
    ]
