# Generated by Django 3.0.1 on 2020-01-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191231_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher')], max_length=2),
        ),
    ]
